spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/auth-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver